# Dockerfile для Frontend - используем готовый build
FROM nginx:alpine

# Копируем готовый собранный фронтенд из папки build
COPY build/ /usr/share/nginx/html/

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порты
EXPOSE 80
EXPOSE 443

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
