apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-super
  namespace: superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-super
  template:
    metadata:
      labels:
        app: admin-super
    spec:
      containers:
      - name: admin-super
        image: uz-superapp-admin-super:latest
        envFrom:
        - configMapRef:
            name: superapp-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-super
  namespace: superapp
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 80
  selector:
    app: admin-super
