apiVersion: v1
kind: Secret
metadata:
  name: superapp-secrets
  namespace: superapp
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  REPL_PASSWORD: repl_password
  JWT_SECRET: superapp-jwt-secret-change-in-production-min-256-bits
  TELEGRAM_BOT_TOKEN: 8655090544:AAEfY-2OB1lljMIwp-Se1bq2pH1R-rCyoD4
  TELEGRAM_CHAT_ID: "6642477034"
